### ISSUE TITLE
Bug while using blockquote

### ISSUE THREAD

**Issue by shreyakurian02** [neetozone/neeto-editor#1251] opened 2024-10-22 13:27 UTC
Ref: https://app.honeybadger.io/projects/122963/faults/113763361

Video: https://shreya-kurian.neetorecord.com/watch/f11a1091-f0e8-4e9c-a062-8e6057adfd32

**Comment by AbhayVAshokan** [comment] 2024-10-22 14:36
@deepakjosp _a

**Comment by deepakjosp** [comment] 2024-10-23 09:36
The root cause is, that there are a few addons passed to the Menu, but not to the Editor. The menu options are generated using the set addons list. Since it's not set on the editor the corresponding commands won't be added to the Editor. In summary, the Editor and the Menu should have the same addons list.

The issue will be fixed by the PR referred [here](https://github.com/bigbinary/neeto-playdash-web/issues/1053).

**Closed as completed by deepakjosp** 2024-10-23 09:36 UTC
Labels: bug
