### ISSUE TITLE
Fix display names for link in articles

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#1096] opened 2024-05-15 07:21 UTC
Ref: https://github.com/bigbinary/neeto-kb-web/issues/6200

https://bigbinary.neetorecord.com/watch/3c8b10aa-31a8-467c-b78a-595774ff588d

bug _t

**Comment by deepakjosp** [comment] 2024-07-05 15:00
Duplicate of https://github.com/bigbinary/neeto-kb-web/issues/6344

**Closed as completed by deepakjosp** 2024-07-05 15:00 UTC
Labels: bug, small
