### ISSUE TITLE
Getting out of number ordered and unordered list

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#861] opened 2023-08-16 22:11 UTC
https://www.loom.com/share/1528557c64a846c0addb29919ea454b8

**Comment by AbhayVAshokan** [comment] 2023-08-21 12:42
@gaagul this issue is pretty hard to reproduce. Doesn't happen all the time. I could only reproduce it once after using neetoKB for some time. But I am not fully sure how to reproduce it. Can you please check if there are issues in Tiptap for this flaky behavior?

**Comment by gaagul** [comment] 2023-08-21 12:45
> @gaagul this issue is pretty hard to reproduce. Doesn't happen all the time. I could only reproduce it once after using neetoKB for some time. But I am not fully sure how to reproduce it. Can you please check if there are issues in Tiptap for this flaky behavior?

I will look into it.

**Comment by gaagul** [comment] 2023-09-06 16:52
Closing this issue since I am not able to reproduce it.
cc: @AbhayVAshokan

**Closed as completed by gaagul** 2023-09-06 16:52 UTC
Labels: 0.5D
