### ISSUE TITLE
Controlling text 

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#828] opened 2023-07-08 18:10 UTC
https://www.loom.com/share/d6f1ed814d2742d0929ffc818796e7ab

https://neetoformhelp.neetokb.com/admin/articles/google-sheets/edit

**Comment by AbhayVAshokan** [comment] 2023-07-10 12:57
@gaagul _a please check this issue.

**Comment by gaagul** [comment] 2023-07-10 13:28
@neerajdotname @AbhayVAshokan The heading node and the paragraph node in the content somehow got merged into one node, I have made changes to the article and the issue is solved, Please take a look at the article, I will close the issue once confirmed.

**Comment by AbhayVAshokan** [comment] 2023-07-10 13:29
@gaagul try to re-create this issue on our side. We need to understand what caused this issue.

**Comment by gaagul** [comment] 2023-07-10 13:33
> @gaagul try to re-create this issue on our side. We need to understand what caused this issue.

I tried recreating the issue from our side and could not do so, That was why i looked into the article itself. I will try different approaches to recreate it.

**Comment by gaagul** [comment] 2023-07-11 09:34
Closing the issue.

**Closed as completed by gaagul** 2023-07-11 09:34 UTC
