### ISSUE TITLE
Multi-line code block not getting inserted using backticks

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#791] opened 2023-06-05 12:18 UTC
https://www.loom.com/share/deda05c29d664e7cb2ee8043b476f6fa

@AbhayVAshokan _a Please take a look.

**Comment by AbhayVAshokan** [comment] 2023-06-06 10:35
@gaagul _a please take a look at the behaviour.

**Comment by gaagul** [comment] 2023-06-09 07:25
@yedhink In this [video](https://www.loom.com/share/53dd729c78804e94bf8c387fdeaa5f31), I demonstrate the steps I took to reproduce the bug. However, despite my efforts, I was unable to recreate the issue on my end. Could you please provide me with the exact content you were trying to insert into the editor? I would like to try it out myself and see if I can identify the problem.

cc: @AbhayVAshokan

**Comment by yedhink** [comment] 2023-06-09 08:06
@gaagul https://www.loom.com/share/6f4bcf3b0f174da6a26ab54987ff1218

```
{
  "chapter_id": "1",
  "lesson_id": "1",
  "paragraph_index": "1",
  "content": "This is the paragraph content."
}
```

**Comment by gaagul** [comment] 2023-06-09 09:02
Closing this issue since tiptap considers "```" as entry point for new codeBlock ("MOD + ALT+ C"  can also open a code-bLock), I have extracted the expected behaviour of the neetoEditor's code-block into a small video: https://www.loom.com/share/0495b3ee1ff4401884d17fd95a65ff8e for reference.

cc: @AbhayVAshokan @yedhink

**Closed as completed by gaagul** 2023-06-09 09:02 UTC
Labels: bug, 0.5D

**Comment by AbhayVAshokan** [comment] 2023-06-09 13:05
@gaagul can you please verify all the different cases that Yedhin pointed out on Tiptap's official website as well: https://tiptap.dev/api/nodes/code-block-lowlight? We need to verify whether this is an issue with Tiptap itself.

**Comment by gaagul** [comment] 2023-06-09 13:19
@AbhayVAshokan backticks whenever at the start of a pragraph node will trigger codeBLock. but backticks which is inserted in between contents of a Paragraph node will not trigger codeBlock, It has to be at the beginning of Paragraph node.
